### ISSUE TITLE
Multiple Words for Menu Button Label Causes Overflow

### ISSUE THREAD

**Issue by garrying** [MaximSiebert/Fiber#21]
![image](https://user-images.githubusercontent.com/227587/40790811-eccd9fca-64c3-11e8-9ac1-626ebdea3a78.png)

**Comment by MaximSiebert** [comment]
Unfortunately I can't quite find a workaround for this. Resulted to removing the label setting and just having 'Menu' as the label. Open to having the mobile hamburger here instead.
